### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lovesegfault** [bemeurer/hemoglobin#2]
Planned features, by importance

- [x] #3 Implement Conway's Game of Life
- [ ] #4 Move to [Termion](https://github.com/ticki/termion)
- [ ] #5 Build basic GUI using [ggez](https://github.com/ggez/ggez)
- [ ] Reorganize project
- [x] #6 Allow for changeable automaton configurations
- [ ] #7 Make new state computation multi-threaded
- [ ] #9 Changeable data structures
- [ ] #8 Allow for saving/loading of world set-ups/configurations (JSON)
- [ ] Fully implement GUI
